### ISSUE TITLE
Cannot start service xx: grpc: the connection is unavailable

### ISSUE THREAD

**Issue by marcossegovia** [docker/docker-snap#27]
Hi there,

Posted recently about and issue then trying to run docker. #26 After successfully having made my defined containers to run for the first time, it took some time after one of the 2 containers crashed and had to make the `sudo docker.compose up` once again. But in this occasion an error just keeps coming up every time I'm trying to execute the command:

```
Cannot start service db: grpc: the connection is unavailable
```

Being `db` a service defined on my `docker.compose.yml` with a connected volume

```
  db:
    image: mangoraft/mongodb-arm
    command: mongod --smallfiles
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
```

What I've tried so far:

- Restart the docker snap service
- Tried to update the service
- Removed the `/data` volume generated by the container

Nothing seems to work.

Thanks beforehand
